version: '3.8'

services:
  github-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION:-dev}
    image: github-mcp-server:${VERSION:-latest}
    container_name: github-mcp-server
    restart: unless-stopped
    ports:
      - "${MCP_PORT:-3000}:${MCP_PORT:-3000}"
    environment:
      # Required variables
      - GITHUB_TOKEN=${GITHUB_TOKEN:?Error: GITHUB_TOKEN environment variable is required}
      
      # Server configuration
      - MCP_PORT=${MCP_PORT:-3000}
      - MCP_HOST=${MCP_HOST:-0.0.0.0}
      - API_BASE_PATH=${API_BASE_PATH:-/api}
      
      # Security settings
      - VALIDATE_TOKENS=${VALIDATE_TOKENS:-true}
      - API_TOKEN=${API_TOKEN:-}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-*}
      - ENABLE_TLS=${ENABLE_TLS:-false}
      - TLS_CERT_PATH=${TLS_CERT_PATH:-}
      - TLS_KEY_PATH=${TLS_KEY_PATH:-}
      
      # Logging settings
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FORMAT=${LOG_FORMAT:-text}
      - LOG_FILE=${LOG_FILE:-}
      
      # Rate limiting
      - GITHUB_RATE_LIMIT=${GITHUB_RATE_LIMIT:-5000}
      - API_RATE_LIMIT=${API_RATE_LIMIT:-60}
      
      # Timeout settings
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT:-30000}
      - GITHUB_API_TIMEOUT=${GITHUB_API_TIMEOUT:-10000}
      
      # Cache settings
      - ENABLE_CACHE=${ENABLE_CACHE:-true}
      - CACHE_TTL=${CACHE_TTL:-300}
      
      # Advanced settings
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - MAX_REQUEST_SIZE=${MAX_REQUEST_SIZE:-5}
      - WORKER_THREADS=${WORKER_THREADS:-0}
    volumes:
      # Optional: Mount TLS certificates if using HTTPS
      - ${TLS_CERT_PATH:-./certs/server.crt}:${TLS_CERT_PATH:-/server/certs/server.crt}:ro
      - ${TLS_KEY_PATH:-./certs/server.key}:${TLS_KEY_PATH:-/server/certs/server.key}:ro
      
      # Optional: Mount log directory if using file logging
      - ${LOG_DIR:-./logs}:/server/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MCP_PORT:-3000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge