# SPARC2 Agent Configuration

[agent]
name = "SPARC2 Agent"
description = "An autonomous agent for code analysis and modification"
default_flow = "analyze_and_modify"

[providers]
  [providers.openai]
  type = "openai"
  api_key_env = "OPENAI_API_KEY"
  default_model = "gpt-4o"
  
  [providers.openrouter]
  type = "openrouter"
  api_key_env = "OPENROUTER_API_KEY"
  default_model = "openai/o3-mini-high"

[flows]
  [flows.analyze_and_modify]
  description = "Analyze code and suggest modifications"
  
  [flows.analyze_and_modify.steps]
    [flows.analyze_and_modify.steps.analyze]
    provider = "openai"
    model = "${providers.openai.default_model}"
    description = "Analyze code for issues and improvements"
    system_prompt = """
    You are a code analysis expert. Analyze the provided code and identify:
    1. Potential bugs or issues
    2. Performance improvements
    3. Readability improvements
    4. Security concerns
    
    Be specific and provide clear explanations for each issue.
    """
    
    [flows.analyze_and_modify.steps.plan]
    provider = "openai"
    model = "${providers.openai.default_model}"
    description = "Plan modifications based on analysis"
    system_prompt = """
    You are a software architect. Based on the code analysis, create a plan for modifications that will address the identified issues.
    
    For each modification:
    1. Describe what will be changed
    2. Explain why this change addresses the issue
    3. Consider any potential side effects
    
    Be specific and provide clear explanations.
    """
    
    [flows.analyze_and_modify.steps.modify]
    provider = "openai"
    model = "${providers.openai.default_model}"
    description = "Implement the planned modifications"
    system_prompt = """
    You are a code modification expert. Implement the planned modifications to the code.
    
    Follow these guidelines:
    1. Make minimal changes to address the specific issues
    2. Maintain the existing code style and patterns
    3. Add comments explaining significant changes
    4. Ensure the code remains functional
    
    Provide the modified code and an explanation of the changes made.
    """
    tools = ["code_analysis", "code_execution"]

  [flows.execute_code]
  description = "Execute code in a secure sandbox"
  
  [flows.execute_code.steps]
    [flows.execute_code.steps.execute]
    provider = "openai"
    model = "${providers.openai.default_model}"
    description = "Execute code in a secure sandbox"
    system_prompt = """
    You are a code execution expert. Execute the provided code in a secure sandbox and return the results.
    
    Follow these guidelines:
    1. Execute the code exactly as provided
    2. Return all output, including errors
    3. Provide execution time and resource usage if available
    
    Ensure the execution is secure and isolated.
    """
    tools = ["code_execution"]

  [flows.checkpoint]
  description = "Create a checkpoint for the current state"
  
  [flows.checkpoint.steps]
    [flows.checkpoint.steps.checkpoint]
    provider = "openai"
    model = "${providers.openai.default_model}"
    description = "Create a checkpoint for the current state"
    system_prompt = """
    You are a version control expert. Create a checkpoint for the current state of the codebase.
    
    Follow these guidelines:
    1. Create a meaningful commit message
    2. Include all relevant files
    3. Ensure the checkpoint is properly recorded
    
    Provide confirmation of the checkpoint creation.
    """
    tools = ["git_operations"]

  [flows.rollback]
  description = "Roll back to a previous checkpoint"
  
  [flows.rollback.steps]
    [flows.rollback.steps.rollback]
    provider = "openai"
    model = "${providers.openai.default_model}"
    description = "Roll back to a previous checkpoint"
    system_prompt = """
    You are a version control expert. Roll back to a previous checkpoint.
    
    Follow these guidelines:
    1. Verify the target checkpoint exists
    2. Ensure all files are properly restored
    3. Confirm the rollback was successful
    
    Provide confirmation of the rollback operation.
    """
    tools = ["git_operations"]